bboss/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("expenses.urls")),
]

expenses/urls.py
from django.urls import path

from . import views

app_name = "expenses"

urlpatterns = [
    path('', views.expense_list, name="list"),
    path('add/', views.expense_create, name="create"),
    path('<int:pk>/',
         views.expense_detail,
         name="detail"),
]

expenses/models.py
from django.db import models


# ORM: Object-Relational Mapper
class Expense(models.Model):
    date = models.DateField()
    amount = models.DecimalField(decimal_places=2, max_digits=12)
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"[#{self.id}] {self.title} @{self.date}"

    def is_expensive(self):
        return self.amount > 1000

expenses/views.py
from django import forms
from django.shortcuts import render, get_object_or_404, redirect

from expenses.models import Expense


def expense_list(request):
    return render(request, "expenses/expense_list.html", {
        'object_list': Expense.objects.order_by("-date"),
    })


def expense_detail(request, pk):
    o = get_object_or_404(Expense, pk=pk)

    return render(request, "expenses/expense_detail.html", {
        'object': o,
    })


#
# class ContactUsForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     age = forms.IntegerField(required=False)
#     message = forms.CharField(widget=forms.Textarea())

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = "__all__"


def expense_create(request):
    if request.method == "POST":
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("expenses:list")
    else:
        form = ExpenseForm()
    return render(request, "expenses/expense_form.html", {
        'form': form,
    })

expenses/templates/expenses/expense_detail.html
<h1>
    BUDGET BOSS: Expense #{{ object.id }}
</h1>
<ul>
    <li><b>Date:</b> {{ object.date }}</li>
    <li><b>Amount:</b> ${{ object.amount }}</li>
    <li><b>Title:</b> {{ object.title }}</li>
    <li><b>Description:</b> {{ object.description|linebreaks }}</li>
</ul>

expenses/templates/expenses/expense_form.html
<h1>Add Expense</h1>
<form method="post" novalidate>
    {% csrf_token %}
    <ul>
        {{ form.as_ul }}
    </ul>

    <button>Add</button>
</form>

expenses/templates/expenses/expense_list.html
<h1>
    BUDGET BOSS
</h1>
<table border="1">
    <tr>
        <th>Date</th>
        <th>Amount</th>
        <th>Title</th>
    </tr>
    {% for object in object_list %}
        <tr>
            <td>{{ object.date }}</td>
            <td>${{ object.amount }}</td>
            <td>
                <a href="{% url "expenses:detail" object.id %}">{{ object.title }}</a>
            </td>
        </tr>
    {% endfor %}
</table>